#!/usr/bin/env bash

set -e

echo "sudo is needed to install into /usr/local/bin/"

sudo install -m 755 <(wget -qO- https://valheim.nikoboi.dev/portal_finder.sh) /usr/local/bin/valheim_portal_finder
sudo install -m 755 <(wget -qO- https://valheim.nikoboi.dev/portal_finder.py) /usr/local/bin/valheim_portal_finder.py

# Testing remnants, keeping for fun.
# sudo install -m 755 portal_finder.sh /usr/local/bin/valheim_portal_finder
# sudo install -m 755 portal_finder.py /usr/local/bin/valheim_portal_finder.py
